name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-lib:
    name: Build Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build .NET
        uses: ./.github/actions/dotnet
        with:
          version: ${{ steps.release-version.outputs.next-version }}${{ github.event.inputs.version && 'pre' || '' }}
